//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApiMarket
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class db_minimarketEntities : DbContext
    {
        public db_minimarketEntities()
            : base("name=db_minimarketEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<tbl_categoria> tbl_categoria { get; set; }
        public virtual DbSet<tbl_marca> tbl_marca { get; set; }
        public virtual DbSet<tbl_producto> tbl_producto { get; set; }
        public virtual DbSet<tbl_proveedor> tbl_proveedor { get; set; }
        public virtual DbSet<tbl_producto_historico> tbl_producto_historico { get; set; }
    
        public virtual ObjectResult<usp_consulta_Productos_Result> usp_consulta_Productos(Nullable<int> opcion, Nullable<int> id)
        {
            var opcionParameter = opcion.HasValue ?
                new ObjectParameter("opcion", opcion) :
                new ObjectParameter("opcion", typeof(int));
    
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_consulta_Productos_Result>("usp_consulta_Productos", opcionParameter, idParameter);
        }
    }
}
